export declare const avatar: string;
export declare const bottom: string;
export declare const counters: string;
export declare const details: string;
export declare const name: string;
export declare const nameDetails: string;
export declare const nameLink: string;
export declare const top: string;
export declare const username: string;
