export declare const flash: string;
export declare const heartWrapper: string;
export declare const rotate: string;
export declare const scale: string;
export declare const set: string;
export declare const shine: string;
export declare const small: string;
export declare const toggled: string;
export declare const wrapper: string;
